// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBanTUjrQK13M0ka6FchgEU5poy6PlYiYg',
    appId: '1:331939658318:web:b8fd48d2867e9511a1611f',
    messagingSenderId: '331939658318',
    projectId: 'forex-signal-6c4cd',
    authDomain: 'forex-signal-6c4cd.firebaseapp.com',
    storageBucket: 'forex-signal-6c4cd.appspot.com',
    measurementId: 'G-5VF0NTSEF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZy6Nrwbe0qG7zDjguF-hI-1ZdEg9n-cA',
    appId: '1:331939658318:android:42be3a398e4b0ff7a1611f',
    messagingSenderId: '331939658318',
    projectId: 'forex-signal-6c4cd',
    storageBucket: 'forex-signal-6c4cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT6FNPpy_wQkucRjNSxC3LIX_qn5b5rAc',
    appId: '1:331939658318:ios:3cd85287bd133bc0a1611f',
    messagingSenderId: '331939658318',
    projectId: 'forex-signal-6c4cd',
    storageBucket: 'forex-signal-6c4cd.appspot.com',
    iosBundleId: 'com.appanda.cryptoSignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT6FNPpy_wQkucRjNSxC3LIX_qn5b5rAc',
    appId: '1:331939658318:ios:1117150f4cc2a8b8a1611f',
    messagingSenderId: '331939658318',
    projectId: 'forex-signal-6c4cd',
    storageBucket: 'forex-signal-6c4cd.appspot.com',
    iosBundleId: 'com.appanda.cryptoSignal.RunnerTests',
  );
}
