// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhuGdu-mgtxEoLnE5atiOcVqEnrQKAaQ',
    appId: '1:1002112642465:web:6bcb2e6957bed656d9efe0',
    messagingSenderId: '1002112642465',
    projectId: 'package-panda',
    authDomain: 'package-panda.firebaseapp.com',
    storageBucket: 'package-panda.appspot.com',
    measurementId: 'G-H7ZXENXNXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABOUCXXF4TTxJ5rBAGY8hRm67a6rMXx6Y',
    appId: '1:1002112642465:android:1b5e39815530c745d9efe0',
    messagingSenderId: '1002112642465',
    projectId: 'package-panda',
    storageBucket: 'package-panda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQvMC_wwNgtXbL2IYAcVAIHBKTbnhVHAg',
    appId: '1:1002112642465:ios:a1f4a8818742f8a4d9efe0',
    messagingSenderId: '1002112642465',
    projectId: 'package-panda',
    storageBucket: 'package-panda.appspot.com',
    iosBundleId: 'com.appanda.packagepanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQvMC_wwNgtXbL2IYAcVAIHBKTbnhVHAg',
    appId: '1:1002112642465:ios:6672ada1127736d6d9efe0',
    messagingSenderId: '1002112642465',
    projectId: 'package-panda',
    storageBucket: 'package-panda.appspot.com',
    iosBundleId: 'com.appanda.packagepanda.RunnerTests',
  );
}
